### PR TITLE
Make lease renewDeadline configurable

### PR DESCRIPTION
**Pull request by phiphi282**
Add a new configuration entry that allow to set the duration the current leader will try to renew its leadership. (This value must always be smaller than LEASE_DURATION)

Additionally set the default duration according to https://godoc.org/k8s.io/client-go/tools/leaderelection#LeaderElectionConfig

LEASE_DURATION: 15
LEASE_RENEW_DEADLINE: 10

### CODE REVIEW

**Comment by phiphi282** [comment]
Fix #44

**Comment by cbeneke** [comment]
Change looks good. Would it eventually be useful to also make the RetryPeriod configurable? I'm fine with leaving it as is, but I don't know if this might induce the same problem^^
Nitpick: The RetryPeriod defaults to 2s in core clients, we might also want to adapt this :)

**Comment by phiphi282** [comment]
I have changed the retry period to 2s now, but if the retryPeriod should be made configurable then it would probably be wise to add to the documentation that these values should only be changed if someone kind of knows how these values work.

Making them for example smaller than the suggested defaults can lead to multiple leaders, in case the clock skew in the cluster is too large.

**Comment by cbeneke** [comment]
Thanks! Might be useful to add the comment (e.g. link to the upstream docs) anyhow. Then I'd say we leave the 2s default as is, if it might come up in the future (which I doubt) this will be an easy change^^

**Pull request merged**
