### PR TITLE
Upgrade kubernetes related packages to version v0.18.2

### PR DESCRIPTION
**Pull request by phiphi282**
Update all kubernetes related packages to v0.18.2
With this update go-client requests will also need a context.
Also the new minimal required go version is 1.13 because of some new reflect functions in the libraries.

This works fine in my test cluster running with kubernetes v1.18.2.
You can test this pull request by changing the image to `phiphi282/hcloud-fip-controller:v0.3.2`

### CODE REVIEW

**Comment by marcocini** [comment]
I have tried the new image. Now in the log there isn't errors but I can find one only line:
`I0421 07:56:42.306110       1 leaderelection.go:242] attempting to acquire leader lease  fip-controller/fip...`
The application seems stuck.

**Comment by phiphi282** [comment]
Maybe the lease was not created correctly. @marcocini  Could you show me the output of:
```
kubectl describe leases.coordination.k8s.io -n fip-controller fip
```

**Comment by marcocini** [comment]
Name:         fip
Namespace:    fip-controller
Labels:       <none>
Annotations:  <none>
API Version:  coordination.k8s.io/v1
Kind:         Lease
Metadata:
  Creation Timestamp:  2019-10-12T09:03:30Z
  Resource Version:    55257813
  Self Link:           /apis/coordination.k8s.io/v1/namespaces/fip-controller/leases/fip
  UID:                 4bbe9c0a-9a0b-428a-b791-273d8eddf98e
Spec:
  Acquire Time:            2020-04-21T10:48:06.547399Z
  Holder Identity:         fip-controller-jj8x9
  Lease Duration Seconds:  30
  Lease Transitions:       67
  Renew Time:              2020-04-21T10:48:06.561143Z
Events:                    <none>

**Comment by phiphi282** [comment]
Can you specifically look into the logs of the pod  fip-controller-jj8x9.
This pod has successfully become the leader, so this pod is the only one that has aquired the lease.
For the other pods it is okay to just show the one line of logs.

**Comment by marcocini** [comment]
```
I0421 10:47:30.616033       1 leaderelection.go:235] attempting to acquire leader lease  fip-controller/fip...
I0421 10:48:06.560846       1 leaderelection.go:245] successfully acquired lease fip-controller/fip
time="2020-04-21T10:48:06Z" level=info msg="Started leading" func="github.com/sirupsen/logrus.(*Logger).Log" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192"
time="2020-04-21T10:48:07Z" level=info msg="Initialization complete. Starting reconciliation" func="github.com/sirupsen/logrus.(*Logger).Log" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192"
```

**Comment by marcocini** [comment]
log for other pods only one line:
`I0421 10:47:30.785594       1 leaderelection.go:235] attempting to acquire leader lease  fip-controller/fip...
`

**Comment by marcocini** [comment]
Thanks

**Comment by phiphi282** [comment]
Nice, that pod now became the leader successfully, that is exactly the behavior we want.
That means that the leaderelection issue should be resolved with this pull request.

close #32 

If there are any problems feel free to open another issue :)

**Comment by phiphi282** [comment]
Nice, that pod now became the leader successfully, that is exactly the behavior we want.
That means that the leaderelection issue should be resolved with this pull request.

close #32 

If there are any problems feel free to open another issue :)

**Comment by cbeneke** [comment]
Thanks for the help there @phiphi282 
My cluster is still running von v1.18.0 so I'm unfortunately not (yet) able to test the changes, but what I can see in both ticket and issue looks good. Merging here. Please use the v0.3.3 release (which I will tag in a few minutes).

Thansk!

**Pull request merged**
